(defun numeric-preprocessor (tbl)
  (let ((classi (table-class tbl)))
    (dolist (eg (egs tbl))
      (doitems (feature i (eg-features eg))
        (let ((column-name (header-name (nth i (table-columns tbl)))))
          (unless (= classi i)
              (unless (unknownp feature)
                (if (numericp column-name)
                  (setf (nth i (eg-features eg)) (log (max 0.0001 feature)))))))))
    tbl))