(defun traintest-pdata()
  (let* ((data (set-data))
         (len (length data))
         (test '())
         (ndx)
         (test-size (floor (* len 0.10))))
    (dotimes (n test-size (list test data))
      (setf ndx (random (length data)))
      (setf test (append (list (nth ndx data)) test))
      (setf data (remove (nth ndx data) data)))))
