(defun median (lst col)
  (let ((median 0)
        (tmp))
    (dolist (i lst)
      (setf tmp (append tmp (list (nth col i)))))
    (setf tmp (sort tmp #'<))
    (if (evenp (length tmp))
        (setf median (+ (nth (/ (length tmp) 2) tmp)
                        (nth (- (/ (length tmp) 2) 1) tmp)))
        (setf median (+ (nth (/ (- (length tmp) 1) 2) tmp))))
    median))

(defun median2 (lst)
  (let ((tmp (copy-list lst))
	(median 0))
    (setf tmp (sort tmp #'<))
    (if (evenp (length tmp))
	(setf median (+ (nth (/ (length tmp) 2) tmp)
			(nth (- (/ (length tmp) 2) 1) tmp)))
	(setf median (+ (nth (/ (- (length tmp) 1) 2) tmp))))
    median))
