(defun nb-batch(&optional (datafile "letter") (outputpath "tmp"))
  (load "miner.lisp")
  (print outputpath)
  (load (concatenate `string outputpath "/" (format nil "~a" datafile) ".lisp"))
  (nb-incremental-test (eval (read-from-string (concatenate `string "("datafile")"))) outputpath)
  (quit)
)
