(defun do-over-features (tbl func)
	(dolist (item (table-all tbl)) 
		(setf (eg-features item) (mapcar func (eg-features item)))))

(defun gimme-classes (tbl)
	(mapcar #'eg-class (table-all tbl)))

(defun count-classes (table)
  (let ((class-count (make-hash-table)) (seen nil) (ranks nil))
    (dolist (x (table-all table)) 
      (if (null (gethash (eg-class x) class-count))
        (setf (gethash (eg-class x) class-count) 1 seen (append seen (list (eg-class x))))
        (setf (gethash (eg-class x) class-count) (+ 1 (gethash (eg-class x) class-count)))
      )
    )
    (dolist (x seen)
      (setf ranks (append ranks (list (list x (gethash x class-count)))))
    )
    ranks
  )
)
