(defun fixes (one tbl &optional (n 1))
  (if (null one) (eg-class (nth n (table-eg tbl))) one))

(defun bayesies (one tbl)
  (if (eql (bayes-classify (eg-features one) (xindex tbl)) (eg-class one))
    1.0
    0.0))

(defun b-squared (tbl &key (percentile .20) (threshhold .80)
                      (score (lambda (b r) (/ (* b b) (+ b r)))))
  (multiple-value-bind (tbl-best tbl-rest) (bore tbl percentile)
    (let* ((acc-best 0)
           (acc-rest 0)
           (range-accs-best (make-hash-table))
           (range-accs-rest (make-hash-table)))
      (macrolet ((bayes-go (which-tbl which-acc)
                   `(dolist (one (table-all ,which-tbl))
                      (let ((value (bayesies one ,which-tbl)))
                        (incf ,which-acc val)
                        (incf (gethash (eg-class one) ,which-range) val)))))
        (bayes-go tbl-best acc-best range-accs-best)
        (bayes-go tbl-rest acc-rest range-accs-rest))
      (subseq (sort (table-columns tbl-best)
                    (lambda (x y)
                      (> (funcall score (fixes (gethash (eg-classp x)
                                                        range-accs-best)
                                               tbl-best))
                         (funcall score (fixes (gethash (eg-classp y)
                                                        range-accs-best)
                                               tbl-best))))
              0 (* threshold (length (table-columns tbl-best)))))
      (subseq (sort (table-columns tbl-rest)
                    (lambda (x y)
                      (> (funcall score (fixes (gethash (eg-classp x)
                                                        range-accs-rest)
                                               tbl-rest))
                         (funcall score (fixes (gethash (eg-classp y)
                                                        range-accs-rest)
                                               tbl-rest))))
              0 (* threshold (length (table-columns tbl-rest))))))))
